version: "3"

services:
  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/Users/asimashfaq/Projects/rss-example/redis 
  mongo:
    image: mongo:3.6
    restart: always
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: app
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo

volumes:
  redis_data:
    driver: local
  mongo:  
networks:
  backend:
    driver: "bridge"